### PR TITLE
Canonicalize dir structure

### PR DESCRIPTION
**Pull request by LorbusChris**
cc @lmzuccarelli

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
@LorbusChris  - So on the whole this looks good.  Should we leave it open and merge once we have deployed and checked it working on MOC

**Comment by LorbusChris** [comment]
These changes are live now and were used for cutting today's releases. @lmzuccarelli please merge at will

**Comment by lmzuccarelli** [comment]
@LorbusChris - great work. Both 4.13 and 4.14 (.NExt) released

**Pull request merged**
